language: python
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
addons:
  apt:
    packages:
    - liblapack-dev
    - libfftw3-dev
install:
  - pip install -r requirements.txt
script:
  - $PIP install cibuildwheel==0.10.0
  - python setup.py test
notifications:
  slack:
    secure: AgUY/TLpOZ8srnEPBMAaRa2QmwwChN7V8HJT6LZcyJVsPVjv7EuashaUMPo7lhTWAqoTnCxCLNtsGkZGvVP3UeIpUJc/LIlGcUl7lD5x9uLHxvyT/5qsW9DS/i1MDQ3cKe6RhxPhe4m1EHRvEgBuv42K94kfNXOZys7Sla7nNWM=
